name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          sudo snap install snapcraft --classic

      - name: Create .env.production file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_SIGNIN_URL: ${{ secrets.VITE_SIGNIN_URL }}
          envkey_VITE_SIGNUP_URL: ${{ secrets.VITE_SIGNUP_URL }}
          envkey_VITE_SOCKET_URL: ${{ secrets.VITE_SOCKET_URL }}
          envkey_VITE_SOCKET_URL_PATH: ${{ secrets.VITE_SOCKET_URL_PATH }}
          envkey_VITE_API_GATEWAY_URL: ${{ secrets.VITE_API_GATEWAY_URL }}
          envkey_VITE_RTMP_URL: ${{ secrets.VITE_RTMP_URL }}
          directory: "./"
          file_name: ".env.production"
          fail_on_empty: true
          sort_keys: false

      - name: Install dependencies
        run: npm install

      - name: Build and Package Electron app
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run build:win
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            npm run build:linux
          fi
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: List generated files
        shell: bash
        run: |
          echo "Listing all files in dist directory:"
          find dist -type f -ls || echo "No files found in dist"
          echo "Listing all files in current directory:"
          ls -la
          
      - name: Create release and upload artifacts to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/flarecast-*-setup.exe
            dist/flarecast *.msi
            dist/flarecast-*.msi
            dist/flarecast.*.msi
            dist/latest.yml
            dist/*.blockmap
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.snap
            dist/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
